version: "3.9"

services:
  devopsdb:
    image: saiyaswanth76/automation:db
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - dbdata:/yaswanth
    deploy:
      replicas: 3
    

  application:
    iimage: saiyaswanth76/automation:app
    restart: always
    ports:
      - "1111:8080"
    networks:
      - mynetwork
    volumes:
      - appdata:/yash
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 64M
      replicas: 3


networks:
  mynetwork:
    driver: overlay

volumes:
  appdata:
  dbdata: 


